2020-04-12 17:27:47,584 ERROR: Exception on /index [GET] [in c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\manuel.robalinho\Google Drive\Trab_Academicos\FLASK\microblog\app\routes.py", line 39, in index
    prev_url=prev_url)
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\manuel.robalinho\Google Drive\Trab_Academicos\FLASK\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\manuel.robalinho\Google Drive\Trab_Academicos\FLASK\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 11, in block "html"
    {%- endblock metas %}
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 13, in block "body"
    {%- block styles %}
  File "C:\Users\manuel.robalinho\Google Drive\Trab_Academicos\FLASK\microblog\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\manuel.robalinho\Google Drive\Trab_Academicos\FLASK\microblog\app\templates\index.html", line 5, in block "app_content"
    <h1>{{ _('Hi, %(username)s!', username=current_user.username) }}</h1>
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\ext.py", line 144, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\ext.py", line 156, in gettext
    return rv % variables
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\markupsafe\__init__.py", line 102, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
ValueError: unsupported format character '!' (0x21) at index 16
2020-04-12 17:27:51,775 ERROR: Exception on /index [GET] [in c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\manuel.robalinho\Google Drive\Trab_Academicos\FLASK\microblog\app\routes.py", line 39, in index
    prev_url=prev_url)
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\manuel.robalinho\Google Drive\Trab_Academicos\FLASK\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\manuel.robalinho\Google Drive\Trab_Academicos\FLASK\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 11, in block "html"
    {%- endblock metas %}
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 13, in block "body"
    {%- block styles %}
  File "C:\Users\manuel.robalinho\Google Drive\Trab_Academicos\FLASK\microblog\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\manuel.robalinho\Google Drive\Trab_Academicos\FLASK\microblog\app\templates\index.html", line 5, in block "app_content"
    <h1>{{ _('Hi, %(username)s!', username=current_user.username) }}</h1>
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\ext.py", line 144, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\ext.py", line 156, in gettext
    return rv % variables
  File "c:\users\manuel.robalinho\appdata\local\programs\python\python37-32\lib\site-packages\markupsafe\__init__.py", line 102, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
ValueError: unsupported format character '!' (0x21) at index 16
2020-04-12 17:31:54,917 INFO: Microblog startup [in C:\Users\manuel.robalinho\Google Drive\Trab_Academicos\FLASK\microblog\app\__init__.py:53]
2020-04-12 17:45:04,827 INFO: Microblog startup [in C:\Users\manuel.robalinho\Google Drive\Trab_Academicos\FLASK\microblog\app\__init__.py:53]
2020-04-12 17:46:02,657 INFO: Microblog startup [in C:\Users\manuel.robalinho\Google Drive\Trab_Academicos\FLASK\microblog\app\__init__.py:53]
2020-04-12 17:52:53,964 INFO: Microblog startup [in C:\Users\manuel.robalinho\Google Drive\Trab_Academicos\FLASK\microblog\app\__init__.py:53]
2020-04-12 18:32:33,677 INFO: Microblog startup [in C:\Users\manuel.robalinho\Google Drive\Trab_Academicos\FLASK\microblog\app\__init__.py:53]
